apiVersion: v1
kind: Namespace
metadata:
  name: noprobes
---
apiVersion: extensions/v1beta1 # for older API controllers
kind: Deployment
metadata:
  labels:
    app: simpleprobe
  name: simpleprobe
  namespace: noprobes
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simpleprobe
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simpleprobe
    spec:
      containers:
      - image: embano1/simpleweb:1.0
        # imagePullPolicy: IfNotPresent # consider using this if image is stable
        imagePullPolicy: Always
        name: simpleweb
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 30Mi
            cpu: 10m
          limits:
            memory: 50Mi
            cpu: 50m
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
