apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleprobe
  name: simpleprobe
  namespace: noprobes
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: simpleprobe
  sessionAffinity: None
  type: NodePort
